<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_mutualFunds</name>
   <tag></tag>
   <elementGuidId>5c4f989a-718e-4e3e-a2e1-bb6bf144ab0a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/ul[1]/li[1]/a[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(1) .container a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'fd-megamenu--desktop__subject' and @href = '/en/investments/mutual-funds/' and (text() = 'Mutual fundsExplore the wide spectrum of available Fidelity mutual funds across different regions, sectors and asset classes.' or . = 'Mutual fundsExplore the wide spectrum of available Fidelity mutual funds across different regions, sectors and asset classes.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.fd-megamenu--desktop__subjects &gt; a:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fd-megamenu--desktop__subject</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/investments/mutual-funds/</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mutual fundsExplore the wide spectrum of available Fidelity mutual funds across different regions, sectors and asset classes.</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:ancestor</name>
      <type>Main</type>
      <value>//div[@data-section-index='0']/div[1]/ul[1]/li[1]/a[2]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href,'/en/investments/mutual-funds/')])[2]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/div/div/ul/li/div/div/ul/li/a[2]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mutual funds 
      															
      															
      															
      														
      															Explore the wide spectrum of available Fidelity mutual funds across different regions, sectors and asset classes.')]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a[2]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
