<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_priceAndPerformance</name>
   <tag></tag>
   <elementGuidId>59a6a8a7-cdc5-4f22-b412-f1c5ca084c9b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/ul[1]/li[1]/a[4]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(1) .container a:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'fd-megamenu--desktop__subject' and @href = '/en/priceandperformance/?view=AG' and (text() = 'Price &amp; performanceView a complete list of funds and find performance summaries, Fund Facts, distributions and more.' or . = 'Price &amp; performanceView a complete list of funds and find performance summaries, Fund Facts, distributions and more.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a:nth-child(4) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fd-megamenu--desktop__subject</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/priceandperformance/?view=AG</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price &amp; performanceView a complete list of funds and find performance summaries, Fund Facts, distributions and more.</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:ancestor</name>
      <type>Main</type>
      <value>//div[@data-section-index='0']/div[1]/ul[1]/li[1]/a[4]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href,'/en/priceandperformance/?view=AG')])[2]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/div/div/ul/li/div/div/ul/li/a[4]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Price &amp; performance
      															
      															
      															
      														
      															View a complete list of funds and find performance summaries, Fund Facts, distributions and more.')]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a[4]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
