<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>62c211e1-59a6-4d3c-9f73-dc4334ed0f79</elementGuidId>
    <imagePath></imagePath>
    <name>link_MutualFunds</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/ul[1]/li[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(1) .container a:nth-of-type(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/investments/mutual-funds/') and equals(@text,'Mutual funds
            
            Explore the wide spectrum of available Fidelity mutual funds across different regions, sectors and asset classes.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.fd-megamenu--desktop__subjects &gt; a:nth-child(2) &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/investments/mutual-funds/</value>
        <webElementGuid>f798a16d-df90-4ae9-8d2f-a335d325ed5c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Mutual funds
        
        Explore the wide spectrum of available Fidelity mutual funds across different regions, sectors and asset classes.</value>
        <webElementGuid>f798a16d-df90-4ae9-8d2f-a335d325ed5c</webElementGuid>
    </webElementProperties>
</WebElementEntity>