<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>db5f9436-4913-469c-92fc-e9f3639bc806</elementGuidId>
    <imagePath></imagePath>
    <name>link_nextDocumentationTopics</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[2]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/nav[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${link_nextDocumentationTopics_class}"] &gt; [class="pagination-nav__link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/docs/quickstart-api-basics') and equals(@text,'Previous
            « API Basics')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_nextDocumentationTopics_internalRoleLinkName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/docs/quickstart-api-basics</value>
        <webElementGuid>64cd0889-0979-4537-af2d-8858b50ddb7f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Previous
        « API Basics</value>
        <webElementGuid>64cd0889-0979-4537-af2d-8858b50ddb7f</webElementGuid>
    </webElementProperties>
</WebElementEntity>