<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b4cbff4d-2559-4090-99b0-5681cdfa341c</elementGuidId>
    <imagePath></imagePath>
    <name>link_richStyling</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="menu__list-item"] [class="menu__list-item"]:nth-child(${link_richStyling_nthChild}) &gt; [class="menu__link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/docs/quickstart-rich-styling') and equals(@text,'Rich Styling')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_richStyling_internalRoleLinkName}"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/docs/quickstart-rich-styling</value>
        <webElementGuid>64cd0889-0979-4537-af2d-8858b50ddb7f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Rich Styling</value>
        <webElementGuid>64cd0889-0979-4537-af2d-8858b50ddb7f</webElementGuid>
    </webElementProperties>
</WebElementEntity>