<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>93cb7fb2-bcab-40cd-86dc-004b1000cfec</elementGuidId>
    <imagePath></imagePath>
    <name>span_headingLevels</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="RichEditor-styleButton\ RichEditor-activeButton"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="${span_headingLevels_internalText}"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>