<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6c2f1582-5cbb-4540-b482-dc8a5bab08c8</elementGuidId>
    <imagePath></imagePath>
    <name>link_ETFs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(1) [class="fd-megamenu--desktop__submenu"] a:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/investments/etfs/') and equals(@text,'ETFs
            
            Look at our mix of exchange-traded funds (ETFs) for various investment goals, even if you’re just starting to invest.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.fd-megamenu--desktop__subject &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/investments/etfs/</value>
        <webElementGuid>f798a16d-df90-4ae9-8d2f-a335d325ed5c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>ETFs
        
        Look at our mix of exchange-traded funds (ETFs) for various investment goals, even if you’re just starting to invest.</value>
        <webElementGuid>f798a16d-df90-4ae9-8d2f-a335d325ed5c</webElementGuid>
    </webElementProperties>
</WebElementEntity>