<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8675fa94-8279-4437-a7ca-9a32f38b146e</elementGuidId>
    <imagePath></imagePath>
    <name>link_investmentFinder</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[3]/div[1]/div[1]/ul[1]/li[1]/a[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/products/investmentfinder/') and equals(@text,'Investment Finder
            
            Search through our products using a wide range of filters and criteria.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Investment Finder Search"i &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/products/investmentfinder/</value>
        <webElementGuid>5996c6db-d4b0-4119-baec-c90bfd237741</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Investment Finder
        
        Search through our products using a wide range of filters and criteria.</value>
        <webElementGuid>5996c6db-d4b0-4119-baec-c90bfd237741</webElementGuid>
    </webElementProperties>
</WebElementEntity>