<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5251a92e-f4c7-47e8-9ffc-58c628fd3bc4</elementGuidId>
    <imagePath></imagePath>
    <name>button_filterAll</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/ti-selection-tool-wrapper[1]/ti-selection-parametric-table[1]/div[1]/ti-selection-tool-action-bar[1]/div[1]/ti-button[1]//button</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-button &gt;&gt; internal:has-text="parametric-filterAll filters"i &gt;&gt; button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>