<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ff866f70-7b53-484e-87f1-103171f41d32</elementGuidId>
    <imagePath></imagePath>
    <name>div_groupTitleBar</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/ti-selection-tool-wrapper[1]/ti-selection-parametric-table[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[3]/div[2]/div[2]/div[11]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(11) &gt; .ag-group &gt; .ag-group-title-bar</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>