<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>18aab7d4-f753-4733-bdaf-ea99f462294f</elementGuidId>
    <imagePath></imagePath>
    <name>div_noUiConnects</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/ti-selection-tool-wrapper[1]/ti-selection-parametric-table[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[3]/div[2]/div[2]/div[11]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/ti-range-slider[1]//div/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.noUi-connects</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>