<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cfa60913-4cca-4da4-b942-3d78e6158bdf</elementGuidId>
    <imagePath></imagePath>
    <name>button_RefreshSection2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/aside[1]/div[1]/div[1]/div[1]/div[1]/span[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="PortalNavigation_pyPortalHarness_1"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'PortalNavigation_pyPortalHarness_1') and equals(@type,'button') and equals(@text,'Refresh this section')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="\32 02303221418310274320"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>PortalNavigation_pyPortalHarness_1</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Refresh this section</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
</WebElementEntity>