<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ed72eeb-d3b2-4f32-bdb4-dd2d5dac1b8d</elementGuidId>
    <imagePath></imagePath>
    <name>button_RefreshSection</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/aside[1]/div[1]/div[1]/div[1]/div[1]/span[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="PortalNavigation_pyPortalHarness_1"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'PortalNavigation_pyPortalHarness_1') and equals(@type,'button') and equals(@text,'Refresh this section')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="\32 02303221418310274320"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>PortalNavigation_pyPortalHarness_1</value>
        <webElementGuid>34c9683e-6bf9-4348-a2bf-ca25f1643f5f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Refresh this section</value>
        <webElementGuid>34c9683e-6bf9-4348-a2bf-ca25f1643f5f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>34c9683e-6bf9-4348-a2bf-ca25f1643f5f</webElementGuid>
    </webElementProperties>
</WebElementEntity>