<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>94e2ae4f-502c-4dcf-b71b-66cb0e5e8b90</elementGuidId>
    <imagePath></imagePath>
    <name>input_CreditCardFeatureType</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[2]/section[1]/div[1]/span[1]/div[1]/span[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\39 7bbb2b402</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'97bbb2b402') and equals(@name,'$PClientPage$pClientDetails$gECIF4082788040$pInterview$pCredCardFeatTypSimplified') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Cash back"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>97bbb2b402</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>$PClientPage$pClientDetails$gECIF4082788040$pInterview$pCredCardFeatTypSimplified</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
</WebElementEntity>