<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e9913abd-274f-485f-b5a1-dedfb8e217a9</elementGuidId>
    <imagePath></imagePath>
    <name>input_SavingsInvestmentsRange</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[2]/section[1]/div[1]/span[1]/div[1]/span[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/span[3]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\31 a039e873</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'1a039e873') and equals(@name,'$PClientPage$pClientDetails$gECIF4082788040$pNonCIBCSavingsInvestmentsRange') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="$100,000 or more"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>1a039e873</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>$PClientPage$pClientDetails$gECIF4082788040$pNonCIBCSavingsInvestmentsRange</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
</WebElementEntity>