<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8952329e-2481-4df5-ac57-4bee0381c3ba</elementGuidId>
    <imagePath></imagePath>
    <name>input_RequestedCreditLimit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[5]/div[1]/ul[1]/li[1]/div[2]/div[1]/span[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\37 a0a402c</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'7a0a402c') and equals(@name,'$PDEMHandler$pOfferPaletteGroups$gCreditCard$pSubGroupList$l1$pPropositions$l3$pRequestedLimit') and equals(@type,'number')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Requested credit limit"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>7a0a402c</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>$PDEMHandler$pOfferPaletteGroups$gCreditCard$pSubGroupList$l1$pPropositions$l3$pRequestedLimit</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>number</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
</WebElementEntity>