<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1b472b89-86a5-49b9-bc03-01435295c5a8</elementGuidId>
    <imagePath></imagePath>
    <name>input_AdvisorTransitNumber</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[2]/section[1]/div[1]/span[1]/div[1]/span[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\39 6149297</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'$PClientPage$pClientDetails$gECIF4082788040$pInterview$pInHouseDetailsPage$pAdvisorTransitNum') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="InhouseAYNQuestions_AdvisorTransitNum"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>$PClientPage$pClientDetails$gECIF4082788040$pInterview$pInHouseDetailsPage$pAdvisorTransitNum</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
</WebElementEntity>