<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cf9224bb-2e92-41c2-b480-2226c1d843bc</elementGuidId>
    <imagePath></imagePath>
    <name>link_AddProductsProgramsOffers</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[2]/section[1]/div[1]/span[1]/div[1]/span[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="Recommendationsheader_pyWorkPage_30bf113f-aded-4e71-bb24-396029a66961"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'Recommendationsheader_pyWorkPage_30bf113f-aded-4e71-bb24-396029a66961') and equals(@text,'Add products, programs and offers')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="Recommendationsheader_programsandoffers"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>Recommendationsheader_pyWorkPage_30bf113f-aded-4e71-bb24-396029a66961</value>
        <webElementGuid>34c9683e-6bf9-4348-a2bf-ca25f1643f5f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add products, programs and offers</value>
        <webElementGuid>34c9683e-6bf9-4348-a2bf-ca25f1643f5f</webElementGuid>
    </webElementProperties>
</WebElementEntity>