<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fca5459f-cf4f-4e89-a97d-1d9cda105b09</elementGuidId>
    <imagePath></imagePath>
    <name>link_SignOff3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/header[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[8]/div[1]/div[1]/div[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="SignOff_pyPortalHarness_84cd91cb-228d-4e52-92a8-a18fa8c5d974"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'SignOff_pyPortalHarness_84cd91cb-228d-4e52-92a8-a18fa8c5d974') and equals(@text,'Sign off')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="ID1624569190038000"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>SignOff_pyPortalHarness_84cd91cb-228d-4e52-92a8-a18fa8c5d974</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign off</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
</WebElementEntity>