<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4b5b118e-f5f4-46d7-a30f-149232011094</elementGuidId>
    <imagePath></imagePath>
    <name>link_CreateNewCase</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[1]/header[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="IntentAndCreateNewButtons_D_ClientOverview_pa1144171496504408pz_98b09853-6d79-41af-88e9-6cb5f3156012"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'IntentAndCreateNewButtons_D_ClientOverview_pa1144171496504408pz_98b09853-6d79-41af-88e9-6cb5f3156012') and equals(@title,'Opens in a new window.') and equals(@text,'Create a new case')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="ClientProfileHeader_CreateNewCase"] &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>IntentAndCreateNewButtons_D_ClientOverview_pa1144171496504408pz_98b09853-6d79-41af-88e9-6cb5f3156012</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Create a new case</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Opens in a new window.</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
</WebElementEntity>