<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2d252821-5754-4804-adfb-4b0f3b88a0cc</elementGuidId>
    <imagePath></imagePath>
    <name>link_RemoveAllProducts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[2]/section[1]/div[1]/span[1]/div[1]/span[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="Recommendationsheader_pyWorkPage_df73c616-488f-45cc-992b-cad4f6ccf27a"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'Recommendationsheader_pyWorkPage_df73c616-488f-45cc-992b-cad4f6ccf27a') and equals(@text,'Remove all products')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="Recommendationsheader_rmproduct"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>Recommendationsheader_pyWorkPage_df73c616-488f-45cc-992b-cad4f6ccf27a</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Remove all products</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
</WebElementEntity>