<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a46f1870-8e62-4f6c-8c05-0494aa8467a6</elementGuidId>
    <imagePath></imagePath>
    <name>link_AddExpense</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[2]/section[1]/div[1]/span[1]/div[1]/span[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/nobr[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="ResidentialDetailsSimplifiedWrapper_ClientPage\.ClientDetails\(ECIF4082788040\)_12"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'ResidentialDetailsSimplifiedWrapper_ClientPage.ClientDetails(ECIF4082788040)_12') and equals(@text,'Add an expense')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="ResidentialDetailsSimplifiedWrapper_addexpense"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>ResidentialDetailsSimplifiedWrapper_ClientPage.ClientDetails(ECIF4082788040)_12</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add an expense</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
</WebElementEntity>