<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d108dde2-b5f5-4075-936e-cb7151f14b0a</elementGuidId>
    <imagePath></imagePath>
    <name>select_ResponseType</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[2]/section[1]/div[1]/span[1]/div[1]/span[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\36 45c8bd7</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'645c8bd7') and equals(@name,'$PClientPage$pClientDetails$gECIF4082788040$pInterview$pInHouseDetailsPage$pResponseType')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="InhouseAYNQuestions_ResponseType"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>645c8bd7</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>$PClientPage$pClientDetails$gECIF4082788040$pInterview$pInHouseDetailsPage$pResponseType</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
</WebElementEntity>