<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b0d22fca-5c18-4a8c-8f4d-2f3baded1a7d</elementGuidId>
    <imagePath></imagePath>
    <name>select_ProductType</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\35 390d5ec</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'5390d5ec') and equals(@name,'$PpyWorkPage$pProductType')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="SelectProductsCompare_ProductType"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>5390d5ec</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>$PpyWorkPage$pProductType</value>
        <webElementGuid>342bb630-dc62-4eb1-9294-1ac23d412bde</webElementGuid>
    </webElementProperties>
</WebElementEntity>