<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9a21c830-1512-47fe-aa87-4e1bf697eb24</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_Description</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/main[1]/div[1]/form[1]/div[3]/div[2]/section[1]/div[1]/span[1]/div[1]/span[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[11]/div[1]/span[1]/span[1]/textarea[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\35 54abcc9</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'554abcc9') and equals(@name,'$PClientPage$pClientDetails$gECIF4082788040$pInterview$pInHouseDetailsPage$ppyDescription')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id="InhouseAYNQuestions_pyDescription"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>554abcc9</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>$PClientPage$pClientDetails$gECIF4082788040$pInterview$pInHouseDetailsPage$ppyDescription</value>
        <webElementGuid>45d88c86-13a9-4800-bf59-fb121f25dcbf</webElementGuid>
    </webElementProperties>
</WebElementEntity>