<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ccabf75c-974b-4d1d-9060-86b4b577af7f</elementGuidId>
    <imagePath></imagePath>
    <name>link_vinothQaDemo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[3]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(3) &gt; [class="flex\ items-center\ px-3\ py-2\ text-sm\ rounded-md\ text-gray-600\ dark\:text-gray-400\ hover\:bg-gray-50\ dark\:hover\:bg-gray-700"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Vinoth QA Demo')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"nav-iframes\\/vinoth-demo\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>7d0cf994-d361-4d61-8c3b-8d39b545bcaa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Vinoth QA Demo</value>
        <webElementGuid>7d0cf994-d361-4d61-8c3b-8d39b545bcaa</webElementGuid>
    </webElementProperties>
</WebElementEntity>