<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_investmentFinder</name>
   <tag></tag>
   <elementGuidId>3e7951f2-3150-420b-929a-8dbe75a8d62c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[3]/div[1]/div[1]/ul[1]/li[1]/a[3]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) a:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'fd-megamenu--desktop__subject' and @href = '/en/products/investmentfinder/' and (text() = 'Investment FinderSearch through our products using a wide range of filters and criteria.' or . = 'Investment FinderSearch through our products using a wide range of filters and criteria.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li:nth-child(3) &gt; .fd-megamenu--desktop__content &gt; .fd-megamenu--desktop__content-container &gt; .fd-megamenu--desktop__submenu &gt; .fd-megamenu--desktop__subjects &gt; a:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fd-megamenu--desktop__subject</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/products/investmentfinder/</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Investment FinderSearch through our products using a wide range of filters and criteria.</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:ancestor</name>
      <type>Main</type>
      <value>//div[@data-section-index='2']/div[1]/ul[1]/li[1]/a[3]</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href,'/en/products/investmentfinder/')])[3]</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/div/div/ul/li[3]/div/div/ul/li/a[3]</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Investment Finder
      															
      															
      															
      														
      															Search through our products using a wide range of filters and criteria.')]</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/ul/li/a[3]</value>
      <webElementGuid>a1fe4a2d-ec6c-4103-9fb1-dfe42ef1a5cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
