<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f440848-fd32-446e-9ebb-e6455b84c2cb</elementGuidId>
    <imagePath></imagePath>
    <name>link_InvestmentFinder</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[3]/div[1]/div[1]/ul[1]/li[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(3) a:nth-of-type(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/products/investmentfinder/') and equals(@text,'Investment Finder
            
            Search through our products using a wide range of filters and criteria.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li:nth-child(3) &gt; .fd-megamenu--desktop__content &gt; .fd-megamenu--desktop__content-container &gt; .fd-megamenu--desktop__submenu &gt; .fd-megamenu--desktop__subjects &gt; a:nth-child(3)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/products/investmentfinder/</value>
        <webElementGuid>f798a16d-df90-4ae9-8d2f-a335d325ed5c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Investment Finder
        
        Search through our products using a wide range of filters and criteria.</value>
        <webElementGuid>f798a16d-df90-4ae9-8d2f-a335d325ed5c</webElementGuid>
    </webElementProperties>
</WebElementEntity>