<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4ffcd1c9-661e-4940-8572-8c2d9ad369fc</elementGuidId>
    <imagePath></imagePath>
    <name>div_ExtensibleAndCustomizable</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[2]/div[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="container"]:nth-child(3)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id="__docusaurus"] div &gt;&gt; internal:has-text="Extensible and CustomizableWe"i &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>