<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4bc71852-bf4e-4b5e-bd70-86952f963d21</elementGuidId>
    <imagePath></imagePath>
    <name>link_Comparators</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/nav[1]/ul[1]/li[2]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(1) &gt; [class="js-megaMenu-level-1\ u-flex"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/amplifier-circuit/comparators/overview.html') and equals(@text,'Comparators')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#responsiveHeader-panel-amplifiers-sub &gt; li &gt; .js-megaMenu-level-1 &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/amplifier-circuit/comparators/overview.html</value>
        <webElementGuid>2ede341c-e8fc-43f1-9be7-d3e19361c3af</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Comparators</value>
        <webElementGuid>2ede341c-e8fc-43f1-9be7-d3e19361c3af</webElementGuid>
    </webElementProperties>
</WebElementEntity>