<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a04538f9-8bf0-4e0b-b285-7c2fec1a59f8</elementGuidId>
    <imagePath></imagePath>
    <name>link_batteryAuthenticationIcs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/nav[1]/ul[1]/li[2]/div[1]/div[1]/div[2]/div[3]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/battery-management/authentication-ics/overview.html') and equals(@text,'Battery authentication ICs')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Battery authentication ICs"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/battery-management/authentication-ics/overview.html</value>
        <webElementGuid>e96337b5-a73e-4870-8191-eebc7b9e1086</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Battery authentication ICs</value>
        <webElementGuid>e96337b5-a73e-4870-8191-eebc7b9e1086</webElementGuid>
    </webElementProperties>
</WebElementEntity>