<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2b31334c-caac-44bd-b6f8-630bdbe66281</elementGuidId>
    <imagePath></imagePath>
    <name>link_TestCases</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiList-root\ MuiList-padding\ css-uej8u9"] &gt; li:nth-of-type(1) &gt; [class="MuiButtonBase-root\ MuiListItemButton-root\ MuiListItemButton-gutters\ MuiListItemButton-root\ MuiListItemButton-gutters\ KatalonListItem-canHover\ css-1lpemu0"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/project/5738/tests/test-cases') and equals(@text,'Test Cases')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Test Cases"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/project/5738/tests/test-cases</value>
        <webElementGuid>da1e726b-b925-4f83-ac7c-f5c35d23f508</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Test Cases</value>
        <webElementGuid>da1e726b-b925-4f83-ac7c-f5c35d23f508</webElementGuid>
    </webElementProperties>
</WebElementEntity>