<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5087449a-560a-469d-b3f3-a743a8a2da12</elementGuidId>
    <imagePath></imagePath>
    <name>link_omcConfirmaion</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/form[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[3]/table[1]/tbody[1]/tr[1]/td[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="A14"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'A14') and equals(@title,'Access Denied') and equals(@href,'#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"OMC Confirmaion\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>5f28a829-7f14-4084-b073-bdaed017f8d8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>A14</value>
        <webElementGuid>5f28a829-7f14-4084-b073-bdaed017f8d8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Access Denied</value>
        <webElementGuid>5f28a829-7f14-4084-b073-bdaed017f8d8</webElementGuid>
    </webElementProperties>
</WebElementEntity>