<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1852ad00-9052-483d-a542-ef75b2517ce7</elementGuidId>
    <imagePath></imagePath>
    <name>div_typeOfMatch</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/ti-xref-wrapper[1]/section[1]/ti-xref-result-wrapper[1]/section[3]/div[1]/ti-xref-main-result-grid[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[3]/div[2]/div[2]/div[3]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(3) &gt; [class="ag-group\ ag-filter-toolpanel-group\ ag-group-item-alignment-stretch\ ag-filter-toolpanel-group-level-0"] &gt; [class="ag-group-title-bar\ ag-filter-toolpanel-group-title-bar\ ag-unselectable\ ag-filter-toolpanel-group-level-0-header\ ag-filter-toolpanel-header"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(3) &gt; .ag-group &gt; .ag-group-title-bar</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>