<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6536ee0d-4868-4d3b-87ee-24c4f25d281b</elementGuidId>
    <imagePath></imagePath>
    <name>span_groupIcon</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/ti-xref-wrapper[1]/section[1]/ti-xref-result-wrapper[1]/section[3]/div[1]/ti-xref-main-result-grid[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/span[2]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(2) &gt; [class="ag-group\ ag-filter-toolpanel-group\ ag-group-item-alignment-stretch\ ag-filter-toolpanel-group-level-0"] &gt; [class="ag-group-title-bar\ ag-filter-toolpanel-group-title-bar\ ag-unselectable\ ag-filter-toolpanel-group-level-0-header\ ag-filter-toolpanel-header"] [class="ag-icon\ ag-icon-tree-closed"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; .ag-group &gt; .ag-group-title-bar &gt; span:nth-child(2) &gt; .ag-icon</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>