<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>eb9533e4-21ec-4651-8813-a9a354326c4f</elementGuidId>
    <imagePath></imagePath>
    <name>span_groupTitle</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/ti-xref-wrapper[1]/section[1]/ti-xref-result-wrapper[1]/section[3]/div[1]/ti-xref-main-result-grid[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/span[2]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ag-filter-toolpanel-group-wrapper\ ag-first-group-visible"] [class="ag-group-title-bar\ ag-filter-toolpanel-group-title-bar\ ag-unselectable\ ag-filter-toolpanel-group-level-0-header\ ag-filter-toolpanel-header"] [class="ag-icon\ ag-icon-tree-closed"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ag-group-title-bar &gt; span:nth-child(2) &gt; .ag-icon &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>