<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dc87f8e3-8715-44a1-bc0e-74a65ef83029</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_enterParts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/ti-xref-wrapper[1]/section[1]/ti-xref-search-page[1]/section[1]/div[3]/div[1]/div[1]/ti-tab-container[1]/ti-tab-panel[1]/div[1]/ti-xref-search-textbox[1]/div[1]/div[1]/ti-xref-partnumber-input[1]/ti-form-element[1]/textarea[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti-xref-partnumber-input-textarea"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>textarea[placeholder=\"Enter up to 30 parts\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>