<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3b3971dd-85c0-47b0-83ad-1aa99db2fd60</elementGuidId>
    <imagePath></imagePath>
    <name>tiButton_clearAll</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/ti-xref-wrapper[1]/section[1]/ti-xref-result-wrapper[1]/section[3]/div[1]/ti-xref-main-result-grid[1]/div[1]/ti-xref-main-result-grid-sticky-footer[1]/div[1]/div[1]/ti-button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-padding-right-6\ sc-ti-xref-main-result-grid-sticky-footer\ ti-button-link\ hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-xref-main-result-grid-sticky-footer ti-button &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>