<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>817874c5-9d93-486f-88fe-ce9f235aa188</elementGuidId>
    <imagePath></imagePath>
    <name>tiButton_allFilters</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/ti-button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti-xref-action-bar-filter-button\ ti-button-has-icon\ ti-button-secondary\ hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-xref-action-bar ti-button &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_cross_reference_search/tiXrefActionBar_object</value>
        <webElementGuid>3ba8e39f-2164-4d4a-925e-ce22c566180d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>3ba8e39f-2164-4d4a-925e-ce22c566180d</webElementGuid>
    </webElementProperties>
</WebElementEntity>