<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1072ce04-4c10-4067-b159-a5ba32549e91</elementGuidId>
    <imagePath></imagePath>
    <name>tiButton_search</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/ti-xref-wrapper[1]/section[1]/ti-xref-search-page[1]/section[1]/div[3]/div[1]/div[1]/ti-tab-container[1]/ti-tab-panel[1]/div[1]/ti-xref-search-textbox[1]/div[1]/div[1]/div[1]/ti-button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-margin-top-2\ ti-button-primary\ hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-tab-panel[aria-label=\"Search part numbers\"] ti-button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>