<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>439bf111-5250-4da0-9321-c8fb24223995</elementGuidId>
    <imagePath></imagePath>
    <name>tiInput_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/ti-xref-wrapper[1]/section[1]/ti-xref-result-wrapper[1]/section[3]/div[1]/ti-xref-main-result-grid[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/span[1]/span[1]/ti-xref-requested-qty-cell[1]/ti-input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[disabled="false"] &gt; [class="hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-input</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>