<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b872f564-6dd5-46f9-b251-ab331fe3e671</elementGuidId>
    <imagePath></imagePath>
    <name>tiInput_object2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//span/ti-xref-requested-qty-cell[1]/ti-input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[disabled="false"] &gt; [class="hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>