<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>47fc7fba-ec10-4618-a787-cc118c618102</elementGuidId>
    <imagePath></imagePath>
    <name>crShadowDom_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-micro-portal-layout[1]/div[1]/main[1]/app-micro-app[1]/app-scoped-styles[1]/cr-shadow-dom[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>cr-shadow-dom</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>cr-shadow-dom</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>