<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>288ec946-7253-4bef-a499-47c52fb8221d</elementGuidId>
    <imagePath></imagePath>
    <name>iframe_clientFrame</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-micro-portal-layout[1]/div[1]/main[1]/app-global-service[1]/app-micro-portal[1]/div[1]/iframe[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="clientFrame"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>iframe[name=\"clientFrame\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>