<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>79cbf48f-28ad-499d-b77a-b04a427f4d49</elementGuidId>
    <imagePath></imagePath>
    <name>link_uploadSites</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/div[1]/app-site-overview[1]/app-site-list-ops-user[1]/cr-cdk-interactive-table[1]/div[1]/div[1]/div[2]/cr-button[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ml-4"] &gt; .button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}?clientUrl={{url}}') and equals(@type,'button') and equals(@text,'+ Upload Sites')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"+ Upload Sites\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}?clientUrl={{url}}</value>
        <webElementGuid>968b33ee-a636-4bfb-ac21-1942fdcdfd15</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>+ Upload Sites</value>
        <webElementGuid>968b33ee-a636-4bfb-ac21-1942fdcdfd15</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>968b33ee-a636-4bfb-ac21-1942fdcdfd15</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Page_dashboard/crShadowDom_object</value>
        <webElementGuid>968b33ee-a636-4bfb-ac21-1942fdcdfd15</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>968b33ee-a636-4bfb-ac21-1942fdcdfd15</webElementGuid>
    </webElementProperties>
</WebElementEntity>