<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aa48f2d1-d17e-4fcb-a80a-17ae00cfff21</elementGuidId>
    <imagePath></imagePath>
    <name>link_sites</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-dashboard-layout[1]/div[1]/main[1]/page-body[1]/div[1]/app-actionbar[1]/div[1]/div[1]/ul[1]/li[5]/div[1]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="es-dropdown\ -es-open"] li:nth-of-type(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Sites') and equals(@href,'{{url}}') and equals(@text,'Sites')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>app-actionbar a[title=\"Sites\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>968b33ee-a636-4bfb-ac21-1942fdcdfd15</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sites</value>
        <webElementGuid>968b33ee-a636-4bfb-ac21-1942fdcdfd15</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Sites</value>
        <webElementGuid>968b33ee-a636-4bfb-ac21-1942fdcdfd15</webElementGuid>
    </webElementProperties>
</WebElementEntity>