<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>169c5258-c907-4974-80a0-7e4e86eb6a2d</elementGuidId>
    <imagePath></imagePath>
    <name>button_SeeAllAwards</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[2]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(2) &gt; [class="fd-gds-component\ fd-common-card"] div:nth-of-type(4) &gt; [class="fd-standard-card--link-text\ fs-standard-card--url\ fd-standard-card--link-text--active"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/en/insights/awards/') and equals(@text,'See all awards')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; .fd-gds-component &gt; .fd-standard-card--regular &gt; .fd-standard-card--text &gt; div:nth-child(4) &gt; .fd-standard-card--link-text</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/insights/awards/</value>
        <webElementGuid>f798a16d-df90-4ae9-8d2f-a335d325ed5c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>See all awards</value>
        <webElementGuid>f798a16d-df90-4ae9-8d2f-a335d325ed5c</webElementGuid>
    </webElementProperties>
</WebElementEntity>