<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>81d7186d-37a1-4d64-9a9d-bc94ba61011b</elementGuidId>
    <imagePath></imagePath>
    <name>link_TextDirection</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/ul[1]/li[11]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="menu__list-item"] [class="menu__list-item"]:nth-child(11) &gt; [class="menu__link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/docs/advanced-topics-text-direction') and equals(@text,'Text Direction')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Text Direction"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/docs/advanced-topics-text-direction</value>
        <webElementGuid>64cd0889-0979-4537-af2d-8858b50ddb7f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Text Direction</value>
        <webElementGuid>64cd0889-0979-4537-af2d-8858b50ddb7f</webElementGuid>
    </webElementProperties>
</WebElementEntity>