<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_investingForBeginners</name>
   <tag></tag>
   <elementGuidId>a316b2bc-6c2c-4eb4-af44-0661a594886b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/div[1]/ul[1]/li[1]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) [class=&quot;fd-megamenu--desktop__submenu&quot;] a:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'fd-megamenu--desktop__subject' and @href = '/en/investor-education/investing-beginners/' and (text() = 'Investing for beginnersWe’ll help you understand the basics of investing.' or . = 'Investing for beginnersWe’ll help you understand the basics of investing.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:text=&quot;Investing for beginners We’ll help you understand the basics of investing.&quot;s >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fd-megamenu--desktop__subject</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/investor-education/investing-beginners/</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Investing for beginnersWe’ll help you understand the basics of investing.</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:ancestor</name>
      <type>Main</type>
      <value>//div[@data-section-index='1']/div[1]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href,'/en/investor-education/investing-beginners/')])[2]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/div/div/ul/li[2]/div/div/ul/li/a</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Investing for beginners 
      															
      															
      															
      														
      															We’ll help you understand the basics of investing.')]</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/ul/li/a</value>
      <webElementGuid>a76786e4-26b2-4e34-8e6e-8ab6334af1ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
