<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ac514e23-ceea-498c-9b66-3b0f6ce39e1e</elementGuidId>
    <imagePath></imagePath>
    <name>link_about</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}about') and equals(@text,'About
            
            Learn more about Test Automation platform')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}about</value>
        <webElementGuid>7d0cf994-d361-4d61-8c3b-8d39b545bcaa</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>About
        
        Learn more about Test Automation platform</value>
        <webElementGuid>7d0cf994-d361-4d61-8c3b-8d39b545bcaa</webElementGuid>
    </webElementProperties>
</WebElementEntity>