<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe4137e5-1839-412b-bc40-c61c656a235f</elementGuidId>
    <imagePath></imagePath>
    <name>link_TestData</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(3) &gt; [class="MuiButtonBase-root\ MuiListItemButton-root\ MuiListItemButton-gutters\ MuiListItemButton-root\ MuiListItemButton-gutters\ KatalonListItem-canHover\ css-1lpemu0"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/project/5738/resources/test-data') and equals(@text,'Test Data')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li:nth-child(3) &gt; .MuiButtonBase-root</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/project/5738/resources/test-data</value>
        <webElementGuid>13b7971b-f76c-4cc2-86db-da6803b65cf9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Test Data</value>
        <webElementGuid>13b7971b-f76c-4cc2-86db-da6803b65cf9</webElementGuid>
    </webElementProperties>
</WebElementEntity>