<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>70662aa7-6c41-466a-a9ed-514505f0e3ac</elementGuidId>
    <imagePath></imagePath>
    <name>link_mdrChecker</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/form[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[5]/table[1]/tbody[1]/tr[1]/td[9]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'MDRChecker') and equals(@title,'Access Denied') and equals(@href,'#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>15826667-7dfa-459c-8929-c5031670997e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>MDRChecker</value>
        <webElementGuid>15826667-7dfa-459c-8929-c5031670997e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Access Denied</value>
        <webElementGuid>15826667-7dfa-459c-8929-c5031670997e</webElementGuid>
    </webElementProperties>
</WebElementEntity>