<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8f185697-7f94-4184-add3-9e96324e1b89</elementGuidId>
    <imagePath></imagePath>
    <name>input_ReceiveMarketingInfo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'receive_marketing_info') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Email me with news and offers"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>receive_marketing_info</value>
        <webElementGuid>923f0c8b-12ca-44e7-b7ac-1aba39b501cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>923f0c8b-12ca-44e7-b7ac-1aba39b501cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>