<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a9d64da6-979a-4eb5-bf22-b0a549e92679</elementGuidId>
    <imagePath></imagePath>
    <name>link_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[3]/ul[1]/li[2]/a[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(2) &gt; [class="flex\ items-center\ px-3\ py-2\ text-sm\ rounded-md\ text-gray-600\ dark\:text-gray-400\ hover\:bg-gray-50\ dark\:hover\:bg-gray-700"] &gt; .lucide</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"nav-iframes\\/cellphone-demo\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>