<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a9c68ada-33fe-4dda-94d5-3cd3513b6718</elementGuidId>
    <imagePath></imagePath>
    <name>label_mobilePhoneModel</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/label[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=dialog &gt;&gt; internal:text="${label_mobilePhoneModel_internalText}"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>