<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>884fc701-b485-4e8b-b232-32292e1e7025</elementGuidId>
    <imagePath></imagePath>
    <name>button_filterOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//button</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti-button-content"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-button &gt;&gt; internal:has-text=/^${button_filterOptions_internalHasText}$/ &gt;&gt; button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_cross_reference_search/tiButton_allFilters</value>
        <webElementGuid>3ba8e39f-2164-4d4a-925e-ce22c566180d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>3ba8e39f-2164-4d4a-925e-ce22c566180d</webElementGuid>
    </webElementProperties>
</WebElementEntity>