<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>57517924-98dc-486e-af70-20b335dd3241</elementGuidId>
    <imagePath></imagePath>
    <name>link_incomeExpenseManagement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[16]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="menu-item\ menu-item-enabled\ menu-item-active"]:nth-child(${link_incomeExpenseManagement_nthChild}) &gt; [class="menu-item-anchor\ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Delete expense')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=menuitem[name="${link_incomeExpenseManagement_internalRoleMenuitemName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Delete expense</value>
        <webElementGuid>84c7a831-a77e-48d3-80c8-c173ece58f8c</webElementGuid>
    </webElementProperties>
</WebElementEntity>