<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>88a5e9b2-d8eb-4dce-b670-1e5a05f31a4a</elementGuidId>
    <imagePath></imagePath>
    <name>link_projectResources</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(${link_projectResources_liNthOfType}) &gt; [class="${link_projectResources_class}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'${path_param_1}/${path_param_2}/${path_param_3}/${path_param_4}') and equals(@text,'Test Data')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="${link_projectResources_internalLabel}"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Test Data</value>
        <webElementGuid>da1e726b-b925-4f83-ac7c-f5c35d23f508</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>${{path_param_1}}/${{path_param_2}}/${{path_param_3}}/${{path_param_4}}</value>
        <webElementGuid>da1e726b-b925-4f83-ac7c-f5c35d23f508</webElementGuid>
    </webElementProperties>
</WebElementEntity>